[package]
name = "cgv-guro-gift-display"
version = "1.2.2"
description = "CGV 구로 경품 안내 Windows desktop application"
authors = ["Seofram"]
license = "UNLICENSED"
repository = "https://github.com/Seofram/cgv-guro-gift-display"
edition = "2024"
rust-version = "1.85"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "cgv_guro_gift_display_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.3" }
tauri-plugin-log = "2"
rusqlite = { version = "0.37", features = ["bundled"] }
